name: Build GGrep Binaries

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build:
    name: Compile for Linux & Mac
    runs-on: ubuntu-latest
    container: golang:1.24-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Make
        run: apk add --no-cache make

      - name: Build for Kubuntu (Linux AMD64)
        run: make build-linux

      - name: Build for Mac (Darwin ARM64)
        run: make build-mac

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: ggrep-binaries
          path: |
            ggrep-linux
            ggrep-mac
          retention-days: 5